"""add subscriptions table

Revision ID: 32229b3de89f
Revises: 4f57afa92297
Create Date: 2026-08-20 18:51:09.279001

Replaces users.is_pro (still present on the table, no longer read by
application code — see app/core/entitlements.py) with a proper
subscriptions row: plan/status/expiry, plus room for a billing-provider
customer ID once Razorpay/Stripe integration lands. 1:1 with users via the
unique index on user_id — zero rows for a user = free tier, by construction.

Backfill: every pre-existing is_pro=True user gets a matching active/pro
row, so nothing loses Pro access the moment this migration applies.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32229b3de89f'
down_revision: Union[str, None] = '4f57afa92297'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=120), nullable=True),
    sa.Column('razorpay_customer_id', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=True)
    # ### end Alembic commands ###

    # Hand-written data migration — autogenerate only produces schema DDL.
    op.execute("""
        INSERT INTO subscriptions (user_id, plan, status, created_at, updated_at)
        SELECT id, 'pro', 'active', now(), now() FROM users WHERE is_pro = true
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
