"""add avatar_url to users

Revision ID: 35db4b3e54d8
Revises: 9fba32d8c615
Create Date: 2026-08-27 21:51:16.389414

Nullable TEXT, no server_default needed — every existing row simply has no
photo yet, which is exactly what NULL already means here. Holds a
`data:image/webp;base64,...` URL written by core/avatar.py (see that
module's docstring for why this isn't a reference into object storage).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35db4b3e54d8'
down_revision: Union[str, None] = '9fba32d8c615'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###
