"""baseline

Revision ID: 4f57afa92297
Revises:
Create Date: 2026-08-20 18:05:35.663887

Creates the full schema from scratch, for any database that doesn't have
it yet (new dev clone, CI, a fresh staging DB). Content = the current ORM
models (app/models.py) exactly, captured via autogenerate against a truly
empty database — so a brand-new DB built by this migration alone ends up
bit-for-bit identical to what the reconciliation below produces.

This establishes Alembic as the schema-versioning tool going forward,
replacing the hand-maintained list of raw `IF NOT EXISTS` ALTER TABLE
strings that used to live in app/core/database.py's init_db(). That list
had, over time, drifted from what the ORM models actually declare:
  - holdings.user_id / watchlist.user_id were added via raw SQL without
    the secondary index the ForeignKey(..., index=True) declarations
    expect (ix_holdings_user_id / ix_watchlist_user_id).
  - users.is_admin / is_pro were added as nullable BOOLEAN DEFAULT FALSE;
    the models declare them non-nullable.
  - watchlist's (user_id, ticker) uniqueness was enforced by a raw-SQL
    index (ix_watchlist_user_ticker) instead of the named constraint the
    model declares (uq_watchlist_user_ticker, see WatchItem.__table_args__
    in app/models.py).

The one database that pre-dates Alembic (the dev Postgres this app was
already running against) was brought to this exact shape via a one-time
manual reconciliation matching the diffs above, then `alembic stamp`-ed at
this revision — so it did NOT run the `create_table` calls below (its
tables already existed); everything after this revision runs identically
for both that database and any fresh one.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f57afa92297'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cache_key', sa.String(length=120), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_cache_cache_key'), 'ai_cache', ['cache_key'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_pro', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=120), nullable=True),
    sa.Column('shares', sa.Float(), nullable=False),
    sa.Column('avg_price', sa.Float(), nullable=False),
    sa.Column('buy_date', sa.Date(), nullable=False),
    sa.Column('sector', sa.String(length=60), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holdings_ticker'), 'holdings', ['ticker'], unique=False)
    op.create_index(op.f('ix_holdings_user_id'), 'holdings', ['user_id'], unique=False)
    op.create_table('portfolio_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.Text(), nullable=True),
    sa.Column('observations', sa.JSON(), nullable=False),
    sa.Column('holdings_sentiment', sa.JSON(), nullable=False),
    sa.Column('truncated', sa.Boolean(), nullable=False),
    sa.Column('shown_holdings', sa.Integer(), nullable=False),
    sa.Column('total_holdings', sa.Integer(), nullable=False),
    sa.Column('incomplete_holdings', sa.JSON(), nullable=False),
    sa.Column('fingerprint', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_reviews_fingerprint'), 'portfolio_reviews', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_portfolio_reviews_user_id'), 'portfolio_reviews', ['user_id'], unique=False)
    op.create_table('price_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=120), nullable=True),
    sa.Column('alert_type', sa.String(length=10), nullable=False),
    sa.Column('target_price', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_alerts_ticker'), 'price_alerts', ['ticker'], unique=False)
    op.create_index(op.f('ix_price_alerts_user_id'), 'price_alerts', ['user_id'], unique=False)
    op.create_table('watchlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=120), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ticker', name='uq_watchlist_user_ticker')
    )
    op.create_index(op.f('ix_watchlist_user_id'), 'watchlist', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_user_id'), table_name='watchlist')
    op.drop_table('watchlist')
    op.drop_index(op.f('ix_price_alerts_user_id'), table_name='price_alerts')
    op.drop_index(op.f('ix_price_alerts_ticker'), table_name='price_alerts')
    op.drop_table('price_alerts')
    op.drop_index(op.f('ix_portfolio_reviews_user_id'), table_name='portfolio_reviews')
    op.drop_index(op.f('ix_portfolio_reviews_fingerprint'), table_name='portfolio_reviews')
    op.drop_table('portfolio_reviews')
    op.drop_index(op.f('ix_holdings_user_id'), table_name='holdings')
    op.drop_index(op.f('ix_holdings_ticker'), table_name='holdings')
    op.drop_table('holdings')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_ai_cache_cache_key'), table_name='ai_cache')
    op.drop_table('ai_cache')
    # ### end Alembic commands ###
