"""add oauth 2fa password-reset columns to users

Revision ID: 9fba32d8c615
Revises: 32229b3de89f
Create Date: 2026-08-21 00:12:31.964619

Single migration, no expand/contract split — every new column is either
nullable or carries a constant server_default, so no old (pre-this-deploy)
app code depends on a shape this migration removes, and no data-dependent
backfill is needed. hashed_password becomes nullable because a Google-only
account (see core/oauth.py) has none; auth_provider distinguishes that case
from "local, password required". is_2fa_enabled/backup_codes get explicit
server_defaults (unlike auth_provider's ORM-only default, these are
NOT NULL columns being added to a table that may already have rows, so a
server-side default is required for the ALTER TABLE to succeed, not just
convenient). totp_secret is written Fernet-encrypted by core/totp.py — never
store or expect plaintext here. password_changed_at is audit-only (see
routers/auth.py's reset-password handler); no auth check reads it — session
revocation on password reset goes through token_store.revoke_all_sessions
instead (Redis, not this column).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fba32d8c615'
down_revision: Union[str, None] = '32229b3de89f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth_provider', sa.String(length=20), server_default='local', nullable=False))
    op.add_column('users', sa.Column('google_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('is_2fa_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('totp_secret', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('backup_codes', sa.JSON(), server_default='[]', nullable=False))
    op.add_column('users', sa.Column('reset_token_hash', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('reset_token_expires_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('password_changed_at', sa.DateTime(), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_index(op.f('ix_users_reset_token_hash'), 'users', ['reset_token_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_reset_token_hash'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.drop_column('users', 'password_changed_at')
    op.drop_column('users', 'reset_token_expires_at')
    op.drop_column('users', 'reset_token_hash')
    op.drop_column('users', 'backup_codes')
    op.drop_column('users', 'totp_secret')
    op.drop_column('users', 'is_2fa_enabled')
    op.drop_column('users', 'google_id')
    op.drop_column('users', 'auth_provider')
    # ### end Alembic commands ###
